services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: safepay-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: safepay-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  mongodb:
    image: mongo:7.0
    container_name: safepay-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: safepay-user-service
    network_mode: "host"
    environment:
      MONGODB_URI: "mongodb://localhost:27017/safePayUser"
    depends_on:
      - mongodb
    restart: always

  transaction_service:
    build:
      context: ./transaction_service
      dockerfile: Dockerfile
    container_name: safepay-transaction-service
    network_mode: "host"
    environment:
      MONGODB_URI: "mongodb://localhost:27017/transactionService"
    depends_on:
      - mongodb
      - kafka
    restart: always

  wallet_service:
    build:
      context: ./wallet_service
      dockerfile: Dockerfile
    container_name: safepay-wallet-service
    network_mode: "host"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://localhost:27017/walletService"
    depends_on:
      - mongodb
    restart: always

  reward_service:
    build:
      context: ./reward_service
      dockerfile: Dockerfile
    container_name: safepay-reward-service
    network_mode: "host"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://localhost:27017/safepay_reward_db"
    depends_on:
      - kafka
      - mongodb
    restart: always

  notification_service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    container_name: safepay-notification-service
    network_mode: "host"
    environment:
      MONGODB_URI: "mongodb://localhost:27017/safepay_notification_db"
    depends_on:
      - kafka
      - mongodb
    restart: always

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: safepay-api-gateway
    network_mode: "host"
    depends_on:
      - user_service
      - transaction_service
      - wallet_service
      - notification_service
      - reward_service
    restart: always

  portal:
    image: nginx:alpine
    container_name: safepay-portal
    network_mode: "host"
    volumes:
      - ./portal:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api_gateway
    restart: always

volumes:
  mongo_data:
